apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: sleep
 annotations:
   initializer.cvgw.me/vault: "true"
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: sleep
   spec:
     containers:
     - name: sleep
       image: tutum/curl
       command: ["/bin/sleep","infinity"]
       imagePullPolicy: IfNotPresent
