kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: initialize-deployments
 namespace: default
subjects:
- kind: ServiceAccount
  name: demo-init
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: deployment-initializer # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

