apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: sleep
 annotations:
   initializer.cvgw.me/annotating: "true"
spec:
 replicas: 1
 template:
   metadata:
     annotations:
       sidecar-injector-webhook.morven.me/inject: "true"
     labels:
       app: sleep
   spec:
     containers:
     - name: sleep
       image: tutum/curl
       command: ["/bin/sleep","infinity"]
       imagePullPolicy: IfNotPresent
